### ISSUE TITLE
DAGMan freesurfer-0.dag finished with exit code 1

### ISSUE THREAD

**Issue by soichih** [pegasus-isi/freesurfer-osg-workflow#2]
I just ran my first freesurfer-osg-workflow on osgconnect, but I can't seem to find the generated output. I believe the job failed, but I can't tell which log to check to see what went wrong. 

On osgconnect, here is the path for the workflow I've submitted.
> /local-scratch/hayashis/workflows/5e03c800cc6723b534bd2d7b/5e03c800cc67234a3ebd2d7e

Could someone help me troubleshoot the problem?

**Comment by rynge** [comment]
Did you use `submit.sh` or your own submit script? It looks like the site catalog was not created correctly, with the `$WORK` directory not being specified.

**Comment by soichih** [comment]
@rynge Yes, I am using a script that is derived from submit.sh. I just ran another workflow, but unfortunately, it failed again. Can you explain what do you mean by site catalog?

I see this file

sites.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<sitecatalog xmlns="http://pegasus.isi.edu/schema/sitecatalog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pegasus.isi.edu/schema/sitecatalog http://pegasus.isi.edu/schema/sc-4.0.xsd" version="4.0">

    <site  handle="local" arch="x86_64">
        <directory type="shared-scratch" path="/public/hayashis/scratch/">
            <file-server operation="all" url="file:///public/hayashis/scratch/"/>
        </directory>
        <directory type="local-storage" path="/outputs/">
            <file-server operation="all" url="file:///outputs/"/>
        </directory>
    </site>

    <!-- this is our execution site -->
    <site  handle="condorpool" arch="x86_64" os="LINUX">
        <profile namespace="pegasus" key="style" >condor</profile>
        <profile namespace="condor" key="universe" >vanilla</profile>
        <profile namespace="condor" key="requirements" >Arch == "X86_64" &amp;&amp; HAS_SINGULARITY == True</profile>

        <!-- always run under singularity -->
        <profile namespace="condor" key="+SingularityImage" >"/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-freesurfer:latest"</profile>
    </site>

</sitecatalog>

```

Here is my entire workdir
> http://dev1.soichi.us/tmp/5ea07d00f98d49bfafaa12a5.5ea07d00f98d495c9daa12a8.tar.gz

I see this in work/freesurfer-0.dag.dagman (1).out which *might be* interesting.. but maybe not?

```
04/22/20 14:06:02 ERROR: the following job(s) failed:
04/22/20 14:06:02 ---------------------- Job ----------------------
04/22/20 14:06:02       Node Name: autorecon1_sh_subject_00001
04/22/20 14:06:02            Noop: false
04/22/20 14:06:02          NodeID: 4
04/22/20 14:06:02     Node Status: STATUS_ERROR    
04/22/20 14:06:02 Node return val: 1
04/22/20 14:06:02           Error: Job failed due to DAGMAN error -1002 and POST Script failed with status 1 (after 2 node retries)
04/22/20 14:06:02 Job Submit File: 00/00/autorecon1_sh_subject_00001.sub
04/22/20 14:06:02     POST Script: /usr/bin/pegasus-exitcode  -s PegasusLite:+exitcode+0 -l freesurfer-0.exitcode.log -M freesurfer-0.cache.meta  .//00/00/autorecon1_sh_subject_00001.out
04/22/20 14:06:02           Retry: 2
04/22/20 14:06:02  HTCondor Job ID: (2111084.0.0)
04/22/20 14:06:02 PARENTS: stage_in_remote_local_0_0 WAITING: 0 CHILDREN: clean_up_local_level_3_0 autorecon2_sh_subject-lh_00003 autorecon2_sh_subject-rh_00002
04/22/20 14:06:02 ---------------------------------------	<END>
04/22/20 14:06:02 Aborting DAG...
04/22/20 14:06:02 Writing Rescue DAG to freesurfer-0.dag.rescue001...
04/22/20 14:06:02 Removing submitted jobs...
04/22/20 14:06:02 Removing any/all submitted HTCondor jobs...
```

I'd be greatly appreciated if you could help me troubleshoot this!

By the way, I'd like to suggest creating a separate log directory - outside of pegasus workdir - where the log files that most freesurfer can understand to be stored, and leave the other logs under the current workdir??

**Comment by rynge** [comment]
I think the real error is:

> ERROR: Systems running GNU glibc version greater than 2.15
>   require a newly formatted license file (it's free). Please
>   download a new one from the following page:
>   http://surfer.nmr.mgh.harvard.edu/registration.html

This can be found in  00/00/autorecon1_sh_subject_00001.out.002

Or if you run `pegasus-analyzer [wfdir]`

**Comment by soichih** [comment]
Oh.. thank you for catching that. 

How did you find the log? I've run pegasus-analyzer but it didn't show the message about freesurfer license.

**Comment by rynge** [comment]
I just looked at the .out.NNN files

Do you still have the workflow in the original location on the filesystem? If so point me to it, and I will see why p-analyzer is not working.

**Comment by soichih** [comment]
Oops.. sorry I just rerun my workflow - which overwrites existing workdir. I will try again later.

**Comment by soichih** [comment]
I think this is the same message I was seeing earlier.

```
$ pegasus-analyzer work
2020-04-29 12:21:49,426:ERROR:Pegasus.db.workflow.stampede_statistics.StampedeStatistics(205): No results found for wf_uuid: 1e65a36a-7ff4-402c-9dec-5c3d58977f70
2020-04-29 12:21:49,426:ERROR:pegasus-analyzer(1076): Failed to load the database.sqlite:////home/hayashis/git/app-freesurfer-osg/work/freesurfer-0.stampede.db
2020-04-29 12:21:49,427:WARNING:pegasus-analyzer(1077): Traceback (most recent call last):
  File "/usr/bin/pegasus-analyzer", line 1070, in analyze_db
    workflow_stats.initialize(wf_uuid)
  File "/usr/lib64/python2.7/site-packages/Pegasus/db/workflow/stampede_statistics.py", line 197, in initialize
    result = q.one ()
  File "/usr/lib64/pegasus/externals/python/sqlalchemy/orm/query.py", line 2215, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()
```

I see the sqlite DB stored here

```
$ ls -la /home/hayashis/git/app-freesurfer-osg/work/freesurfer-0.stampede.db
-rw-r--r-- 1 hayashis osg 323584 Apr 29 03:40 /home/hayashis/git/app-freesurfer-osg/work/freesurfer-0.stampede.db
```
